apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "dev"
  resource: "category"
  rules:
    - actions:
        - create
      effect: EFFECT_ALLOW
      roles:
        - USER

    - actions:
        - update
        - destroy
      effect: EFFECT_ALLOW
      roles:
        - USER

    # - actions:
    #     - create
    #     - read
    #     - update
    #     - delete
    #   effect: EFFECT_ALLOW
    #   derivedRoles:
    #     - admin
