name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "6342414-a0e9fbbe-25c6-441b-b980-34f67f80ac26" -e "6342414-17a76e3e-17f5-49fd-827c-8250435dd19c" --integration-id "161320-${{ github.run_id }}"
